export const qz = [
  {id:1,subject:"수학",title:"산수문제",
  content:"1더하기3은 뭔가요?",grade:1,answer:3,folder_id:1,
  choices: ['2', '3', '4', '5']},
  {id:2,subject:"국어",title:"국업문제",
  content:"김소월은 누구인가요?",grade:2,answer:4,folder_id:2,
  choices: ['나', '너', '우리', '그']},
  {id:3,subject:"영어",title:"eng?eng?",
  content:"what is that?",grade:3,answer:3,folder_id:3,
  choices: ['수박', '당근', '사과', '파인애플']},
  {id:4,subject:"수학",title:"더하기를해요",
  content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmodLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmodLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmodLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod",grade:1,answer:3,folder_id:2,
  choices: ['수박', '당근', '사과', '파인애플']},
  {id:5,subject:"수학",title:"빼기문제",
  content:"1-3은 -2이다!?",grade:6, answer:3,folder_id:2,
  choices: ['아니다', '맞다', '몰라', '알게뭐야']},
  {id:6,subject:"국어",title:"국업문제",
  content:"김소월은 누구인가요?",grade:5, answer:3,folder_id:2,
  choices: ['코끼리', '기린', '사람', '공룡']},
  {id:7,subject:"영어",title:"eng?eng?",
  content:"what is that?",grade:4, answer:3,folder_id:3,
  choices: ['수박', '당근', '사과', '파인애플']},
  {id:8,subject:"사회",title:"산수문제",
  content:"김소월은 누구인가요?",grade:3, answer:4,folder_id:2,
  choices: ['나', '너', '우리', '그']},
  {id:9,subject:"과학",title:"빼기문제",
  content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmodLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmodLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmodLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod",grade:1,answer:3,folder_id:2,
  choices: ['수박', '당근', '사과', '파인애플']},
  {id:10,subject:"기타",title:"국업문제",
  content:"1-3은 -2이다!?",grade:2,answer:1, folder_id:2,
  choices: ['아니다', '맞다', '몰라', '알게뭐야']},
]

export const myfd = [
  {folder_id: 1, folder_name:'어렵네'},
  {folder_id: 2, folder_name:'보통'},
  {folder_id: 3, folder_name:'쉽구만'},
  {folder_id: 4, folder_name:'국'},
  {folder_id: 5, folder_name:'영'},
  {folder_id: 6, folder_name:'수'},
]

